name: WakaTime stats
on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/wakatime-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
